[producer]
kafka.nodes = [
	"node1:9092",
	"node2:9092",
]
kafka.version = "2.8.0"
kafka.topic = "some_dst_topic"
kafka.tls = true
kafka.tls-cafile = "/path/to/ca.crt"
kafka.tls-certfile = "/path/to/cert.crt"
kafka.tls-keyfile = "/path/to/cert.key"
kafka.tls-skip-verify = false
kafka.username = "kafka"
kafka.password = "kafka"
compression = "snappy"
#Partitioner: hash, keepPartition, random
partitioner = "hash"
flush.fequency = 1s
flush.bytes = 5388608

[consumer]
kafka.nodes = [
	"node1:9092",
	"node2:9092",
]
kafka.topic = "some_dst_topic"
kafka.tls = true
kafka.tls-cafile = "/path/to/ca.crt"
kafka.tls-certfile = "/path/to/cert.crt"
kafka.tls-keyfile = "/path/to/cert.key"
kafka.tls-skip-verify = false
kafka.username = "kafka"
kafka.password = "kafka"
group.id = "my-consumer-group"
offset.retention = 1h

[graphite]
address = "metrics.lan:2003"
prefix = "some.$hostname"
interval = 30s
metric.logging = false