[producer]
kafka.nodes = [
	"node1:9092",
	"node2:9092",
]
kafka.topic = "some_dst_topic"
kafka.tls = true
kafka.username = "kafka"
kafka.password = "kafka"
compression = "snappy"
#Partitioner: hash, keepPartition, random
partitioner = "hash"
flush.fequency = 1s
flush.bytes = 5388608

[consumer]
group.id = "my-consumer-group"
topic = "mytopic"

[graphite]
address = "metrics.lan:2003"
prefix = "some.$hostname"
interval = 30s
